[package]
name = "css-layout-box-model"
version = "0.1.0"
edition = "2021"
rust-version = "1.75"

[dependencies]
# Component dependencies
css-types = { path = "../css_types" }
css-stylist-core = { path = "../css_stylist_core" }

[dev-dependencies]
